ronggoAdmin/buku_tabungan/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'tabungan_blueprint',
    __name__,
    url_prefix='/',
    template_folder='templates',
    static_folder='static'
)

ronggoAdmin/buku_tabungan/routes.py
from ronggoAdmin.buku_tabungan import blueprint
from flask import Flask, render_template, redirect, url_for, request, make_response, session
import alregcode
from alregcode import regGenerate
from ronggoAdmin.models import models
from ronggoAdmin import db

@blueprint.route('/tabungan')
def tabungan():
 
    kode = models.Tabungan.query.order_by(models.Tabungan.kode_urutan.desc()).first()
    
    if isinstance(kode,type(None)):
        kodereg = regGenerate("TB-",None,3)
    else:
        kodereg =regGenerate("TB-",kode.kode_urutan,3)

    tabungan = models.Tabungan.query.filter_by(status=1)
    data = models.Tabungan.query.filter_by(status=0)
    inc = regGenerate.inc


    
    dataT = models.Nasabah.query.all()
    return render_template('tabungan.html', tabungan = tabungan, data=data, kodereg=kodereg,inc=inc)

@blueprint.route('/tabungan/tambah', methods=["POST"])
def tambahTabungan():
    
    kode = request.form.get("kode")
    kode_urutan = request.form.get("kode_urutan")
    tanggal = request.form.get("tanggal")
    debet = request.form.get("debet")
    saldo = request.form.get("saldo")
   
    dataTabungan = models.Tabungan(
        
        kode_urutan = kode_urutan,
        kode = kode,
        tanggal = tanggal,
        debet = debet,
        saldo = saldo,
        status = 1


    )


    db.session.add(dataTabungan)
    db.session.commit()

    return redirect(url_for('tabungan_blueprint.tabungan' ))


@blueprint.route('/tabungan/update', methods=["POST"])
def tabunganUpdate():

    kode = request.form.get("kode")
    tanggal = request.form.get("tanggal")
    debet = request.form.get("debet")
    saldo = request.form.get("saldo")

    tabungan = models.Tabungan.query.filter_by(kode=kode).first()
    tabungan.tanggal = tanggal
    tabungan.debet = debet
    tabungan.saldo = saldo
   
    db.session.commit()
    
    return redirect(url_for('tabungan_blueprint.tabungan'))


@blueprint.route('/tabungan/edit/<kode>',methods=["GET"])
def tabunganEdit(kode):
    
    tabungan = models.Tabungan.query.filter_by(kode=kode).first()

    return render_template('tabungan_edit.html', tabungan=tabungan)


@blueprint.route('/tabungan/delete/<kode>', methods=["GET"])
def tabunganDelete(kode):

    tabungan = models.Tabungan.query.filter_by(kode=kode).first()
    tabungan.status = 0

    db.session.commit()
    return redirect(url_for('tabungan_blueprint.tabungan'))


@blueprint.route('/tabungan/restore/<kode>', methods=["GET"])
def tabunganRestore(kode):

    tabungan = models.Tabungan.query.filter_by(kode=kode).first()
    tabungan.status = 1

    db.session.commit()

    return redirect(url_for('tabungan_blueprint.tabungan'))


@blueprint.route('/tabungan/deletep/<kode>', methods=["GET"])
def tabunganDeletep(kode):

    tabungan = models.Tabungan.query.filter_by(kode=kode).first()

    db.session.delete(tabungan)
    db.session.commit()

    return redirect(url_for('tabungan_blueprint.tabungan'))

ronggoAdmin/buku_tabungan/templates/tabungan_edit.html
{% extends "base.html" %}

{% block title %} Dashboard {% endblock title %}

{% block stylesheets %}
{{ super() }}
{% endblock stylesheets %}

{% block content %}

<body class="skin-blue fixed-layout">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="loader">
            <div class="loader__figure"></div>
            <p class="loader__label">Ronggo</p>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">

        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <div class="row page-titles">
                    <div class="col-md-5 align-self-center">
                        <h4 class="text-themecolor">Data Tabungan</h4>
                    </div>
                    <div class="col-md-7 align-self-center text-right">
                        <div class="d-flex justify-content-end align-items-center">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                                <li class="breadcrumb-item active">Datatable</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <form class="form p-t-20" action="{{url_for('tabungan_blueprint.tabunganUpdate')}}"
                                    method="POST">
                                    <div class="form-group">
                                        <label for="exampleInputuname">Kode Tabungan</label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-user-o"></i></span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Kode Tabungan"
                                                name="kode_tabungan" required="required" value="{{tabungan.kode}} "
                                                readonly>
                                        </div>

                                    </div>
                                    <div class="form-group">
                                            <label>Kode Nasabah</label>
                                            <div class="input-group mb-3">
                                                <div class="input-group-prepend">
                                                    <span class="input-group-text"><i class="fa fa-ticket"></i></span>
                                                </div>
                                                <select name="kodeN" class="form-control">
                                                    <option>--- pilih ---</option>
                                                    <option>{{tabungan.kodeN}}</option>
                                                    <select
                                            </div>
    
                                        </div>
                                    <div class="form-group">
                                        <label>Tanggal
                                           </label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i
                                                        class="fa fa-birthday-cake"></i></span>
                                            </div>
                                            <input type="date" class="form-control" placeholder="Tanggal Lahir"
                                                name="tanggal" required="required"
                                                value="{{tabungan.tanggal}}">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label>Alamat</label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-map"></i></span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Alamat" name="debet"
                                                required="required" value="{{tabungan.debet}}">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label>Email
                                            address</label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-email"></i></span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="saldo" name="saldo"
                                                aria-describedby="basic-addon2" required="required"
                                                value="{{tabungan.saldo}}">
                                        </div>

                                    </div>
                        

                                    <input type="hidden" value="{{ tabungan.kode }}" name="kode">

                                    <div class="modal-footer">
                                        <button type="submit"
                                            class="btn btn-success waves-effect waves-light">Update</button>
                                        <button type="button" class="btn btn-info waves-effect text-left"
                                            data-dismiss="modal">Kembali</button>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>

                    <!-- ============================================================== -->
                    <!-- End Right sidebar -->
                    <!-- ============================================================== -->
                </div>
                <!-- ============================================================== -->
                <!-- End Container fluid  -->
                <!-- ============================================================== -->
            </div>

        </div>


</body>
{% endblock content %}

{% block javascripts %}
{{ super()}}
<script>
    $(document).ready(function () {
        $('#myTable').DataTable();
        $(document).ready(function () {
            var table = $('#example').DataTable({
                "columnDefs": [{
                    "visible": false,
                    "targets": 2
                }],
                "order": [
                    [2, 'asc']
                ],
                "displayLength": 25,
                "drawCallback": function (settings) {
                    var api = this.api();
                    var rows = api.rows({
                        page: 'current'
                    }).nodes();
                    var last = null;
                    api.column(2, {
                        page: 'current'
                    }).data().each(function (group, i) {
                        if (last !== group) {
                            $(rows).eq(i).before(
                                '<tr class="group"><td colspan="5">' + group +
                                '</td></tr>');
                            last = group;
                        }
                    });
                }
            });
            // Order by the grouping
            $('#example tbody').on('click', 'tr.group', function () {
                var currentOrder = table.order()[0];
                if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                    table.order([2, 'desc']).draw();
                } else {
                    table.order([2, 'asc']).draw();
                }
            });
        });
    });
    $('#example23').DataTable({
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    });
</script>

{% endblock javascripts %}