ronggoAdmin/transaksi/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'transaksi_blueprint',
    __name__,
    url_prefix='/',
    template_folder='templates',
    static_folder='static'
)

ronggoAdmin/transaksi/routes.py
from ronggoAdmin.transaksi import blueprint
from flask import Flask, render_template, redirect, url_for, request, make_response, session
import alregcode
from alregcode import regGenerate
from ronggoAdmin.models import models
from ronggoAdmin import db

@blueprint.route('/transaksi',methods=["GET"])
def transaksi():

    kode = models.Transaksi.query.order_by(models.Transaksi.kode_urutan.desc()).first()

    if isinstance(kode,type(None)):
        kodereg = regGenerate("T-",None,3)
    else:
        kodereg =regGenerate("T-",kode.kode_urutan,3)

    transaksi = models.Transaksi.query.filter_by(status=1)
    data = models.Transaksi.query.filter_by(status=0)
    inc = regGenerate.inc

    query = ("SELECT * FORM transaksi")
    connect = db.engine.connect()
    cursor = connect.cursor()
    cursor.execute(query)
    record = cursor.fethall()



    dataTr = models.Nasabah.query.order_by(models.Nasabah.kode.desc()).first()


    return render_template('transaksi.html', transaksi = transaksi, data=data, kodereg=kodereg,inc=inc,dataTr=dataTr)

@blueprint.route('/transaksi/tambah', methods=["POST"])
def tambahTransaksi():

    kode = request.form.get("kode")
    kode_urutan = request.form.get("kode_urutan")
    nama = request.form.get("nama")
    jenis_transaksi = request.form.get("jenis_transaksi")
    tanggal =  request.form.get("tanggal")
    jumlah_transaksi = request.form.get("jumlah_transaksi")
    tujuan_transaksi = request.form.get("tujuan_transaksi")
    status_transaksi = request.form.get("status_transaksi") 

    
    

    dataTransaksi = models.Transaksi(
        kode_urutan = kode_urutan,
        kode = kode,
        nama = nama,
        jenis_transaksi =jenis_transaksi,
        tanggal = tanggal,
        jumlah_transaksi = jumlah_transaksi,
        tujuan_transaksi = tujuan_transaksi,
        status_transaksi = status_transaksi,
        status = 1
       
    )

    db.session.add(dataTransaksi)
    db.session.commit()

    return redirect(url_for('transaksi_blueprint.transaksi'))

@blueprint.route('/transaksi/update', methods=["POST"])
def transaksiUpdate():

    kode = request.form.get("kode")
    nama = request.form.get("nama")
    jenis_transaksi = request.form.get("jenis_transaksii")
    tanggal =  request.form.get("tanggal")
    jumlah_transaksi = request.form.get("jumlah_transaksi")
    tujuan_transaksi = request.form.get("tujuan_transaksi")
    status_transaksi = request.form.get("Status_transaksi") 

    


    transaksi = models.Transaksi.query.filter_by(kode=kode).first()

  
    transaksi.nama = nama
    transaksi.jenis_transaksi = jenis_transaksi
    transaksi.tanggal = tanggal
    transaksi.jumlah_transaksi = jumlah_transaksi
    transaksi.tujuan_transaksi = tujuan_transaksi
    transaksi.status_transaksi = status_transaksi
   
    db.session.commit()
    
    return redirect(url_for('transaksi_blueprint.transaksi'))


@blueprint.route('/transaksi/edit/<kode>',methods=["GET"])
def transaksiEdit(kode):
    
    transaksi = models.Transaksi.query.filter_by(kode=kode).first()

    return render_template('transaksi_edit.html', transaksi=transaksi)


@blueprint.route('/transaksi/delete/<kode>', methods=["GET"])
def transaksiDelete(kode):

    transaksi = models.Transaksi.query.filter_by(kode=kode).first()
    transaksi.status = 0

    db.session.commit()
    return redirect(url_for('transaksi_blueprint.transaksi'))


@blueprint.route('/transaksi/restore/<kode>', methods=["GET"])
def transaksiRestore(kode):

    transaksi = models.Transaksi.query.filter_by(kode=kode).first()
    transaksi.status = 1

    db.session.commit()

    return redirect(url_for('transaksi_blueprint.transaksi'))


@blueprint.route('/transaksi/deletep/<kode>', methods=["GET"])
def transaksiDeletep(kode):

    transaksi = models.Transaksi.query.filter_by(kode=kode).first()

    db.session.delete(transaksi)
    db.session.commit()

    return redirect(url_for('transaksi_blueprint.transaksi'))

ronggoAdmin/transaksi/templates/transaksi_edit.html
{% extends "base.html" %}

{% block title %} Dashboard {% endblock title %}

{% block stylesheets %}
{{ super() }}
{% endblock stylesheets %}

{% block content %}

<body class="skin-blue fixed-layout">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="loader">
            <div class="loader__figure"></div>
            <p class="loader__label">Ronggo</p>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">

        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <div class="row page-titles">
                    <div class="col-md-5 align-self-center">
                        <h4 class="text-themecolor">Edit Transaksi</h4>
                    </div>
                    <div class="col-md-7 align-self-center text-right">
                        <div class="d-flex justify-content-end align-items-center">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                                <li class="breadcrumb-item ">Data Transaksi</li>
                                <li class="breadcrumb-item active">Edit Transkasi </li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <form class="form p-t-20" action="{{url_for('transaksi_blueprint.transaksiUpdate')}}"
                                    method="POST">
                                    <div class="form-group">
                                        <label for="exampleInputuname">Kode Transaksi</label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-user-o"></i></span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Kode Transkasi"
                                                name="kode_transaksi" required="required" value="{{transaksi.kode}} "
                                                readonly>
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label>Nama</label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-user-o"></i></span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Nama" name="nama"
                                                required="required" value="{{transaksi.nama}}">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label>Jenis Transaksi
                                            </label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-map"></i></span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Jenis Transaksi"
                                                name="tempat_lahir" required="required"
                                                value="{{transaksi.jenis_transaksi}}">
                                        </div>
                                    </div>
                                    <div class="form-group">
                                        <label>Tanggal
                                            </label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i
                                                        class="fa fa-birthday-cake"></i></span>
                                            </div>
                                            <input type="date" class="form-control" placeholder="Tanggal"
                                                name="tanggal_lahir" required="required"
                                                value="{{transaksi.tanggal}}">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label>Jumlah Transaksi</label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-map"></i></span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Alamat" name="jumlah_transaksi"
                                                required="required" value="{{transaksi.jumlah_transaksi}}">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label>Tujuan Transaksi</label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-email"></i></span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Tujuan Transaksi" name="tujuan_transaksi"
                                                aria-describedby="basic-addon2" required="required"
                                                value="{{transaksi.tujuan_transaksi}}">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label for="pwd1">Status Transaksi</label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-mobile-phone"></i></span>
                                            </div>
                                            <input type="tel" class="form-control" placeholder="Status Transaksi"
                                                name="Status_transaksi" required="required" value="{{transaksi.Status_transaksi}}">
                                        </div>
                                    </div>

                                    <input type="hidden" value="{{ transaksi.kode }}" name="kode">

                                    <div class="modal-footer">
                                        <button type="submit"
                                            class="btn btn-success waves-effect waves-light">Update</button>
                                        <button type="button" class="btn btn-info waves-effect text-left"
                                            data-dismiss="modal">Kembali</button>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>

                    <!-- ============================================================== -->
                    <!-- End Right sidebar -->
                    <!-- ============================================================== -->
                </div>
                <!-- ============================================================== -->
                <!-- End Container fluid  -->
                <!-- ============================================================== -->
            </div>

        </div>


</body>
{% endblock content %}

{% block javascripts %}
{{ super()}}


{% endblock javascripts %}