ronggoAdmin/sampah/__init__.py
from flask import Blueprint

blueprint = Blueprint(
    'sampah_blueprint',
    __name__,
    url_prefix='/',
    template_folder='templates',
    static_folder='static'
)

ronggoAdmin/sampah/routes.py
from ronggoAdmin.sampah import blueprint
from flask import Flask, render_template, redirect, url_for, request, make_response, session
import alregcode
from alregcode import regGenerate
from ronggoAdmin.models import models
from ronggoAdmin import db

@blueprint.route('/sampah',methods=["GET"])
def sampah():
    kode = models.Sampah.query.order_by(models.Sampah.kode_urutan.desc()).first()

    if isinstance(kode,type(None)):
        kodereg = regGenerate("S-",None,3)
    else:
        kodereg =regGenerate("S-",kode.kode_urutan,3)

    sampah = models.Sampah.query.filter_by(status=1)
    data = models.Sampah.query.filter_by(status=0)
    inc = regGenerate.inc
    
    query = ("SELECT kode FROM nasabah")
    connection = db.engine.connect()
    result = connection.execute(query)
    fect= result.fetchall()
    for i in fect:
        record = i
        

    nasabah_id = models.Nasabah.query.order_by(models.Nasabah.kode.desc()).first()


    return render_template('sampah.html', sampah = sampah, data=data, kodereg=kodereg,inc=inc,nasabah_id=nasabah_id,record=record)

@blueprint.route('/sampah/tambah', methods=["POST"])
def tambahSampah():
    kode = request.form.get("kode")
    kode_urutan = request.form.get("kode_urutan")
    tanggal =request.form.get("tanggal")
    jenis_sampah =request.form.get("jenis_sampah")
    berat_sampah = request.form.get("berat_sampah")
    harga = request.form.get("harga")

    dataSampah = models.Sampah(
        kode_urutan = kode_urutan,
        kode = kode,
        tanggal =tanggal,
        jenis_sampah = jenis_sampah,
        berat_sampah = berat_sampah,
        harga = harga,
        status = 1
    )

    db.session.add(dataSampah)
    db.session.commit()

    return redirect(url_for('sampah_blueprint.sampah'))

@blueprint.route('/sampah/update', methods=["POST"])
def sampahUpdate():

    kode = request.form.get("kode")
    tanggal = request.form.get("tanggal")
    jenis_sampah =request.form.get("jenis_sampah")
    berat_sampah = request.form.get("berat_sampah")
    harga = request.form.get("harga")

    sampah = models.Sampah.query.filter_by(kode=kode).first()
    
    sampah.tanggal =tanggal
    sampah.jenis_sampah =jenis_sampah
    berat_sampah = berat_sampah
    harga = harga
   
    db.session.commit()
    
    return redirect(url_for('sampah_blueprint.sampah'))


@blueprint.route('/sampah/edit/<kode>',methods=["GET"])
def sampahEdit(kode):
    
    sampah = models.Sampah.query.filter_by(kode=kode).first()

    return render_template('sampah_edit.html', sampah=sampah)


@blueprint.route('/sampah/delete/<kode>', methods=["GET"])
def sampahDelete(kode):

    sampah = models.Sampah.query.filter_by(kode=kode).first()
    sampah.status = 0

    db.session.commit()
    return redirect(url_for('sampah_blueprint.sampah'))


@blueprint.route('/sampah/restore/<kode>', methods=["GET"])
def sampahRestore(kode):

    sampah = models.Sampah.query.filter_by(kode=kode).first()
    sampah.status = 1

    db.session.commit()

    return redirect(url_for('sampah_blueprint.sampah'))


@blueprint.route('/sampah/deletep/<kode>', methods=["GET"])
def sampahDeletep(kode):

    sampah = models.Sampah.query.filter_by(kode=kode).first()

    db.session.delete(sampah)
    db.session.commit()

    return redirect(url_for('sampah_blueprint.sampah'))

ronggoAdmin/sampah/templates/sampah_edit.html
{% extends "base.html" %}

{% block title %} Dashboard {% endblock title %}

{% block stylesheets %}
{{ super() }}
{% endblock stylesheets %}

{% block content %}

<body class="skin-blue fixed-layout">
    <!-- ============================================================== -->
    <!-- Preloader - style you can find in spinners.css -->
    <!-- ============================================================== -->
    <div class="preloader">
        <div class="loader">
            <div class="loader__figure"></div>
            <p class="loader__label">Ronggo</p>
        </div>
    </div>
    <!-- ============================================================== -->
    <!-- Main wrapper - style you can find in pages.scss -->
    <!-- ============================================================== -->
    <div id="main-wrapper">

        <div class="page-wrapper">
            <!-- ============================================================== -->
            <!-- Container fluid  -->
            <!-- ============================================================== -->
            <div class="container-fluid">
                <!-- ============================================================== -->
                <!-- Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <div class="row page-titles">
                    <div class="col-md-5 align-self-center">
                        <h4 class="text-themecolor">Data Nasabah</h4>
                    </div>
                    <div class="col-md-7 align-self-center text-right">
                        <div class="d-flex justify-content-end align-items-center">
                            <ol class="breadcrumb">
                                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                                <li class="breadcrumb-item active">Datatable</li>
                            </ol>
                        </div>
                    </div>
                </div>
                <!-- ============================================================== -->
                <!-- End Bread crumb and right sidebar toggle -->
                <!-- ============================================================== -->
                <!-- ============================================================== -->
                <!-- Start Page Content -->
                <!-- ============================================================== -->
                <div class="row">
                    <div class="col-lg-12">
                        <div class="card">
                            <div class="card-body">
                                <form class="form p-t-20" action="{{url_for('sampah_blueprint.sampahUpdate')}}"
                                    method="POST">
                                    <div class="form-group">
                                        <label for="exampleInputuname">Kode Sampah</label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-ticket"></i></span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Kode Nasabah"
                                                name="kode_sampah" required="required" value="{{sampah.kode}} "
                                                readonly>
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label>Tanggal</label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-calendar"></i></span>
                                            </div>
                                            <input type="date" class="form-control" placeholder="Tanggal"
                                                name="tanggal" required="required" value="{{sampah.tanggal}}">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label>Jenis Sampah
                                            </label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i
                                                        class="fa fa-window-restore"></i></span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="jenis_sampah"
                                                name="jenis_sampah" required="required"
                                                value="{{sampah.jenis_sampah}}">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label>Berat sampah</label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-balance-scale"></i></span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Berat Sampah (kg)" name="berat_sampah"
                                                required="required" value="{{sampah.berat_sampah}} kg">
                                        </div>

                                    </div>
                                    <div class="form-group">
                                        <label>Harga
                                            </label>
                                        <div class="input-group mb-3">
                                            <div class="input-group-prepend">
                                                <span class="input-group-text"><i class="fa fa-tag"></i></span>
                                            </div>
                                            <input type="text" class="form-control" placeholder="Harga" name="harga"
                                                aria-describedby="basic-addon2" required="required"
                                                value="Rp.&nbsp;{{sampah.harga}}">
                                        </div>

                                    </div>
                                    

                                    <input type="hidden" value="{{ sampah.kode }}" name="kode">

                                    <div class="modal-footer">
                                        <button type="submit"
                                            class="btn btn-success waves-effect waves-light">Update</button>
                                        <button type="button" class="btn btn-info waves-effect text-left"
                                            data-dismiss="modal">Kembali</button>
                                    </div>

                                </form>
                            </div>
                        </div>
                    </div>

                    <!-- ============================================================== -->
                    <!-- End Right sidebar -->
                    <!-- ============================================================== -->
                </div>
                <!-- ============================================================== -->
                <!-- End Container fluid  -->
                <!-- ============================================================== -->
            </div>

        </div>


</body>
{% endblock content %}

{% block javascripts %}
{{ super()}}
<script>
    $(document).ready(function () {
        $('#myTable').DataTable();
        $(document).ready(function () {
            var table = $('#example').DataTable({
                "columnDefs": [{
                    "visible": false,
                    "targets": 2
                }],
                "order": [
                    [2, 'asc']
                ],
                "displayLength": 25,
                "drawCallback": function (settings) {
                    var api = this.api();
                    var rows = api.rows({
                        page: 'current'
                    }).nodes();
                    var last = null;
                    api.column(2, {
                        page: 'current'
                    }).data().each(function (group, i) {
                        if (last !== group) {
                            $(rows).eq(i).before(
                                '<tr class="group"><td colspan="5">' + group +
                                '</td></tr>');
                            last = group;
                        }
                    });
                }
            });
            // Order by the grouping
            $('#example tbody').on('click', 'tr.group', function () {
                var currentOrder = table.order()[0];
                if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                    table.order([2, 'desc']).draw();
                } else {
                    table.order([2, 'asc']).draw();
                }
            });
        });
    });
    $('#example23').DataTable({
        dom: 'Bfrtip',
        buttons: [
            'copy', 'csv', 'excel', 'pdf', 'print'
        ]
    });
</script>

{% endblock javascripts %}